import { MigrationInterface, QueryRunner } from 'typeorm'

export class UpdateBaseEntityAddUpdateAt1659370021745 implements MigrationInterface {
  name = 'UpdateBaseEntityAddUpdateAt1659370021745'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "referral_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_card_weight_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(
      `ALTER TABLE "user_card_random_blood_sugar_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`,
    )
    await queryRunner.query(
      `ALTER TABLE "user_card_fasting_blood_sugar_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`,
    )
    await queryRunner.query(
      `ALTER TABLE "user_card_after_meal_blood_sugar_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`,
    )
    await queryRunner.query(`ALTER TABLE "user_card_ldl_level_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(
      `ALTER TABLE "user_card_triglyceride_level_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`,
    )
    await queryRunner.query(`ALTER TABLE "user_card_hba1c_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(
      `ALTER TABLE "user_card_blood_pressure_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`,
    )
    await queryRunner.query(`ALTER TABLE "user_card_steps_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_card_profile_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_card_water_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_card_sleep_history_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_card_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "storage_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_medications_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "triggers_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_articles_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "gallery_article_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "medications_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_videos_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "gallery_video_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "conditions_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_conditions_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "gender_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "race_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "procedures_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_procedures_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_journey_survey_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_lifestyle_survey_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_reminders_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "target_group_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "gallery_recipe_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_recipes_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "appointments_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_appointments_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_additional_information_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "country_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "state_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "city_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "notification_predefined_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "notification_custom_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "food_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_tracks_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "track_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "track_group_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "track_group_line_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "profile_photo_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "notification_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_admin_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_settings_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
    await queryRunner.query(`ALTER TABLE "user_notifications_entity" ADD "updateAt" TIMESTAMP DEFAULT now()`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "user_notifications_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_settings_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_admin_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "notification_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "profile_photo_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "track_group_line_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "track_group_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "track_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_tracks_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "food_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "notification_custom_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "notification_predefined_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "city_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "state_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "country_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_additional_information_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_appointments_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "appointments_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_recipes_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "gallery_recipe_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "target_group_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_reminders_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_lifestyle_survey_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_journey_survey_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_procedures_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "procedures_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "race_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "gender_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_conditions_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "conditions_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "gallery_video_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_videos_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "medications_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "gallery_article_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_articles_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "triggers_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_medications_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "storage_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_sleep_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_water_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_profile_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_steps_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_blood_pressure_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_hba1c_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_triglyceride_level_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_ldl_level_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_after_meal_blood_sugar_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_fasting_blood_sugar_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_random_blood_sugar_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "user_card_weight_history_entity" DROP COLUMN "updateAt"`)
    await queryRunner.query(`ALTER TABLE "referral_entity" DROP COLUMN "updateAt"`)
  }
}
