FROM node:17.9.0-alpine
ARG NODE_OPTIONS
ENV NODE_OPTIONS $NODE_OPTIONS
ARG DATABASE_HOST
ENV DATABASE_HOST $DATABASE_HOST
ARG DATABASE_USER
ENV DATABASE_USER $DATABASE_USER
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ARG POSTGRES_DB
ENV POSTGRES_DB $POSTGRES_DB
ARG DATABASE_PORT
ENV DATABASE_PORT $DATABASE_PORT
ARG APP_PORT
ENV APP_PORT $APP_PORT
ARG RUN_MODE
ENV RUN_MODE $RUN_MODE
ARG GLOBAL_PREFIX
ENV GLOBAL_PREFIX $GLOBAL_PREFIX
ARG MIRGATIONS_RUN
ENV MIRGATIONS_RUN $MIRGATIONS_RUN
ARG PASSWORD_HASH
ENV PASSWORD_HASH $PASSWORD_HASH
ARG COGNITO_CLIENT_ID
ENV COGNITO_CLIENT_ID $COGNITO_CLIENT_ID
ARG COGNITO_REGION
ENV COGNITO_REGION $COGNITO_REGION
ARG COGNITO_POOL_ID
ENV COGNITO_POOL_ID $COGNITO_POOL_ID
ARG AWS_ACCESS_KEY
ENV AWS_ACCESS_KEY $AWS_ACCESS_KEY
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ARG COGNITO_CLIENT_ID_ADMIN
ENV COGNITO_CLIENT_ID_ADMIN $COGNITO_CLIENT_ID_ADMIN
ARG COGNITO_POOL_ID_ADMIN
ENV COGNITO_POOL_ID_ADMIN $COGNITO_POOL_ID_ADMIN
ARG WEB_ADMIN_SECRET_ACCESS_TOKEN
ENV WEB_ADMIN_SECRET_ACCESS_TOKEN $WEB_ADMIN_SECRET_ACCESS_TOKEN
ARG S3_REGION
ENV S3_REGION $S3_REGION
ARG S3_ENDPOINT
ENV S3_ENDPOINT $S3_ENDPOINT
ARG STORAGE_S3_BUCKET_NAME
ENV STORAGE_S3_BUCKET_NAME $STORAGE_S3_BUCKET_NAME
ARG SES_REGION
ENV SES_REGION $SES_REGION
ARG SES_ENDPOINT
ENV SES_ENDPOINT $SES_ENDPOINT
ARG SES_SOURCE
ENV SES_SOURCE $SES_SOURCE
ARG SES_TO_ADDRESS
ENV SES_TO_ADDRESS $SES_TO_ADDRESS
ARG CLOUDWATCH_GROUP
ENV CLOUDWATCH_GROUP $CLOUDWATCH_GROUP
ARG CLOUDWATCH_STREAM
ENV CLOUDWATCH_STREAM $CLOUDWATCH_STREAM
ARG MAILCHIMP_API_KEY
ENV MAILCHIMP_API_KEY $MAILCHIMP_API_KEY
ARG MAILCHIMP_SERVER_PREFIX
ENV MAILCHIMP_SERVER_PREFIX $MAILCHIMP_SERVER_PREFIX
ARG MAILCHIMP_DEFAULT_AUDIENCE_ID
ENV MAILCHIMP_DEFAULT_AUDIENCE_ID $MAILCHIMP_DEFAULT_AUDIENCE_ID
ARG CHROMIUM_PATH
ENV CHROMIUM_PATH $CHROMIUM_PATH
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ARG TMP_DIR_PATH
ENV TMP_DIR_PATH $TMP_DIR_PATH
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ARG FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID $FIREBASE_PROJECT_ID
ARG FIREBASE_PRIVATE_KEY_ID
ENV FIREBASE_PRIVATE_KEY_ID $FIREBASE_PRIVATE_KEY_ID
ARG FIREBASE_PRIVATE_KEY
ENV FIREBASE_PRIVATE_KEY $FIREBASE_PRIVATE_KEY
ARG FIREBASE_CLIENT_ID
ENV FIREBASE_CLIENT_ID $FIREBASE_CLIENT_ID
ARG FIREBASE_CLIENT_EMAIL
ENV FIREBASE_CLIENT_EMAIL $FIREBASE_CLIENT_EMAIL

WORKDIR /app

COPY . .

RUN apk add --no-cache chromium

RUN yarn install --production=false --frozen-lockfile

# Add user so we don't need --no-sandbox.
RUN addgroup -S pptruser && adduser -S -G pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads /app \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

# Run everything after as non-privileged user.
USER pptruser


RUN ["chmod", "+x", "entrypoint.sh"]

ENTRYPOINT [ "./entrypoint.sh" ]