export enum SuccessCodes {
  EmailConfirmedSuccessfully = 'EMAIL_CONFIRMED_SUCCESSFULLY',
  ReferralAddedSuccessfully = 'REFERRAL_ADDED_SUCCESSFULLY',
  RestorePasswordEmailSentSuccessfully = 'RESTORE_PASSWORD_EMAIL_SENT_SUCCESSFULLY',
  RestoreUsernameExecuteSuccessfully = 'RESTORE_USERNAME_EXECUTE_SUCCESSFULLY',
  RestorePasswordConfirmedSuccessfully = 'RESTORE_PASSWORD_CONFIRMED_SUCCESSFULLY',
  RefreshTokenRevokedSuccessfully = 'REFRESH_TOKEN_REVOKED_SUCCESSFULLY',
  AccountDetailsUpdated = 'ACCOUNT_DETAILS_UPDATED_SUCCESSFULLY',
  AssessmentPersonalInfoUpdated = 'ASSESSMENT_PERSONAL_INFO_UPDATED_SUCCESSFULLY',
  AssessmentSummaryInfoUpdated = 'ASSESSMENT_SUMMARY_INFO_UPDATED_SUCCESSFULLY',

  LanguageUpdated = 'USER_LANGUAGE_UPDATED_SUCCESSFULLY',
  MeasurementsUpdated = 'USER_MEASUREMENTS_UPDATED_SUCCESSFULLY',
  PasswordChanged = 'PASSWORD_CHANGED_SUCCESSFULLY',

  EmailSent = 'EMAIL_SENT_SUCCESSFULLY',

  BloodSugarSaved = 'BLOOD_SUGAR_SAVED_SUCCESSFULLY',
  WeightSaved = 'WEIGHT_WAS_SAVED_SUCCESSFULLY',
  UserConditionResolved = 'USER_CONDITION_WAS_RESOLVED_SUCCESSFULLY',
  UserConditionSaved = 'USER_CONDITION_WAS_SAVED_SUCCESSFULLY',
  BloodPressureSaved = 'BLOOD_PRESSURE_WAS_SAVED_SUCCESSFULLY',
  LdlSaved = 'LDL_WAS_SAVED_SUCCESSFULLY',
  TriglyceridesSaved = 'TRIGLYCERIDES_WAS_SAVED_SUCCESSFULLY',
  Hba1cSaved = 'HBA1C_WAS_SAVED_SUCCESSFULLY',
  StepsSaved = 'STEPS_WAS_SAVED_SUCCESSFULLY',

  UserMedicationCreated = 'USER_MEDICATION_CREATED_SUCCESSFULLY',
  UserMedicationUpdated = 'USER_MEDICATION_UPDATED_SUCCESSFULLY',
  UserMedicationDeleted = 'USER_MEDICATION_DELETED_SUCCESSFULLY',

  UserAppointmentCreated = 'USER_APPOINTMENT_CREATED_SUCCESSFULLY',
  UserAppointmentUpdated = 'USER_APPOINTMENT_UPDATED_SUCCESSFULLY',
  UserAppointmentDeleted = 'USER_APPOINTMENT_DELETED_SUCCESSFULLY',

  UserProcedureCreated = 'USER_PROCEDURE_CREATED_SUCCESSFULLY',
  UserProcedureUpdated = 'USER_PROCEDURE_UPDATED_SUCCESSFULLY',
  UserProcedureDeleted = 'USER_PROCEDURE_DELETED_SUCCESSFULLY',

  UserTrackCreated = 'USER_TRACK_CREATED_SUCCESSFULLY',
  UserTrackUpdated = 'USER_TRACK_UPDATED_SUCCESSFULLY',
  UserTrackDeleted = 'USER_TRACK_DELETED_SUCCESSFULLY',

  UserNotificationUpdated = 'USER_NOTIFICATION_UPDATED_SUCCESSFULLY',
  UserNotificationDeleted = 'USER_NOTIFICATION_DELETED_SUCCESSFULLY',

  UserReminderUpdated = 'USER_REMINDER_UPDATED_SUCCESSFULLY',
  UserReminderDeleted = 'USER_REMINDER_DELETED_SUCCESSFULLY',

  UserSettingsUpdated = 'USER_SETTINGS_UPDATED_SUCCESSFULLY',

  SleepRecordCreated = 'SLEEP_RECORD_WAS_SAVED_SUCCESSFULLY',

  WaterRecordSaved = 'WATER_RECORD_WAS_SAVED_SUCCESSFULLY',

  WellnessJourneyItemUpdated = 'WELLNESS_JOURNEY_ITEM_WAS_UPDATED',

  UserDeviceCreated = 'USER_DEVICE_CREATED_SUCCESSFULLY',
  UserDeviceDeleted = 'USER_DEVICE_DELETED_SUCCESSFULLY',
}
